# Generated by Django 4.1 on 2022-08-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="description",
        ),
    ]
