# Generated by Django 4.1 on 2022-08-22 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendant",
            name="attendant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendant",
            name="clas",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clases",
                to="classes.class",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendant",
            unique_together={("clas", "attendant")},
        ),
    ]
