# Generated by Django 4.1 on 2022-08-19 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "attend_status",
                    models.CharField(
                        choices=[
                            ("subscribe", "Subscribe"),
                            ("unsubscribe", "Unsubscribe"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "attendant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clases",
                        to="classes.class",
                    ),
                ),
            ],
            options={
                "unique_together": {("clas", "attendant")},
            },
        ),
    ]
