# Generated by Django 4.1 on 2022-08-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_attendant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendant",
            name="attend_status",
        ),
    ]
