# Generated by Django 4.1 on 2022-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Event start time"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Event start time"
            ),
        ),
    ]
