# Generated by Django 4.1 on 2022-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Event Name"
            ),
        ),
    ]
