# Generated by Django 4.1 on 2022-08-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
