# Generated by Django 4.1 on 2022-08-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=6,
                verbose_name="Trainer Gener",
            ),
        ),
    ]
