# Generated by Django 4.1 on 2022-08-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={},
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="created",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="subscription start date"
            ),
        ),
    ]
